version: "3.6"
services:
  db:
    image: "postgres:12-alpine"
    restart: unless-stopped
    ports:
      - "15432:5432"
    volumes:
      - ./etc/postgres_data:/var/lib/postgresql/data
    env_file: ./.env

  redis:
    image: "redis:latest"
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./etc/redis_data:/data
