version: "3.6"
services:
  db:
    image: "postgres:12-alpine"
    restart: unless-stopped
    ports:
      - "15432:5432"
    volumes:
      - ./etc/postgres_data:/var/lib/postgresql/data
    env_file: ./.env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    expose:
      - "5672"
    ports:
      - "5672:5672"
    volumes:
      - ./etc/rabbitmqdata:/var/lib/rabbitmq
